name: 'Security Scan with TITAN Inference Model'
description: 'Runs security scans calling inference model with customizable file exclusions'

inputs:
  api_base_url:
    description: 'URL for the backend API'
    required: true
  report_format:
    description: 'The report output format type (md|pdf|xml)'
    required: false
    default: 'md'
  timeout_seconds:
    description: 'Timeout to call the API before failing (in seconds)'
    required: false
    default: '300'
  exclude_files:
    description: 'Comma-separated list of file patterns to exclude from scanning (glob)'
    required: false
    default: ''
  blocking:
    description: 'Whether this step is blocking (fail on issues) or non-blocking'
    required: false
    default: 'true'
  block_percentage:
    description: 'Percentage of files with issues required to block (default: 50)'
    required: false
    default: '50'

runs:
  using: 'composite'
  steps:
    - name: Setup PDF generation tools
      if: ${{ inputs.report_format == 'pdf' }}
      shell: bash
      run: |
        echo "Setting up PDF generation tools..."
        
        # Check if Node.js is available
        if command -v node >/dev/null 2>&1; then
          echo "✅ Node.js is available"
          node_version=$(node --version)
          echo "Node.js version: $node_version"
        else
          echo "❌ Node.js not found"
          exit 1
        fi
        
        # Install md2pdf for PDF generation
        echo "Installing md2pdf for reliable PDF generation..."
        if npm install -g md2pdf; then
          echo "✅ md2pdf installed successfully"
          
          # Debug npm configuration
          echo "[DEBUG] npm global bin directory: $(npm bin -g 2>/dev/null || echo 'not found')"
          echo "[DEBUG] npm global root directory: $(npm root -g 2>/dev/null || echo 'not found')"
          echo "[DEBUG] Current PATH: $PATH"
          
          # Refresh PATH and verify installation
          export PATH="$(npm bin -g):$PATH"
          echo "[DEBUG] Updated PATH: $PATH"
          
          # Test different ways to access md2pdf
          if command -v md2pdf >/dev/null 2>&1; then
            echo "✅ md2pdf found in PATH"
            md2pdf --version 2>/dev/null || echo "md2pdf command available"
          elif command -v npx >/dev/null 2>&1; then
            echo "✅ md2pdf accessible via npx"
            npx md2pdf --version 2>/dev/null || echo "md2pdf available via npx"
          else
            echo "⚠️ md2pdf command not directly accessible, will use alternative methods"
            
            # Additional debug info
            echo "[DEBUG] Checking for md2pdf in common locations:"
            ls -la "$(npm bin -g)" 2>/dev/null | grep md2pdf || echo "  - Not found in npm bin -g"
            ls -la "$(npm root -g)/md2pdf/bin/" 2>/dev/null || echo "  - Not found in npm root -g/md2pdf/bin/"
            ls -la "/usr/local/bin/" 2>/dev/null | grep md2pdf || echo "  - Not found in /usr/local/bin"
          fi
        else
          echo "❌ Failed to install md2pdf"
          exit 1
        fi
      
    - name: Run security scan with SSE
      id: scan
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        chmod +x ./entrypoint.sh
        ./entrypoint.sh
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        REPORT_FORMAT: ${{ inputs.report_format }}
        TIMEOUT_SECONDS: ${{ inputs.timeout_seconds }}
        EXCLUDE_FILES: ${{ inputs.exclude_files }}
        BLOCKING: ${{ inputs.blocking }}
        BLOCK_PERCENTAGE: ${{ inputs.block_percentage }}
      
