name: 'Security Scan with TITAN Inference Model'
description: 'Runs security scans calling inference model with customizable file exclusions'

inputs:
  api_base_url:
    description: 'URL for the backend API'
    required: true
  report_format:
    description: 'The report output format type (md|pdf|xml)'
    required: false
    default: 'md'
  timeout_seconds:
    description: 'Timeout to call the API before failing (in seconds)'
    required: false
    default: '300'
  exclude_files:
    description: 'Comma-separated list of file patterns to exclude from scanning (glob)'
    required: false
    default: ''
  blocking:
    description: 'Whether this step is blocking (fail on issues) or non-blocking'
    required: false
    default: 'true'
  block_percentage:
    description: 'Percentage of files with issues required to block (default: 50)'
    required: false
    default: '50'

runs:
  using: 'composite'
  steps:
    - name: Setup PDF generation tools
      if: ${{ inputs.report_format == 'pdf' }}
      shell: bash
      run: |
        echo "Setting up PDF generation tools..."
        
        # Check if Node.js is available (preferred method)
        if command -v node >/dev/null 2>&1; then
          echo "✅ Node.js is available for PDF generation"
          node_version=$(node --version)
          echo "Node.js version: $node_version"
        else
          echo "❌ Node.js not found"
        fi
        
        # Install Chrome for PDF generation
        echo "Installing Chrome for headless PDF generation..."
        sudo apt-get update -qq
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update -qq
        sudo apt-get install -y google-chrome-stable
        
        # Verify Chrome installation
        if command -v google-chrome >/dev/null 2>&1; then
          echo "✅ Chrome installed successfully"
          google-chrome --version
        else
          echo "⚠️ Chrome installation may have failed, checking alternatives..."
          if command -v chromium-browser >/dev/null 2>&1; then
            echo "✅ Chromium browser available as fallback"
            chromium-browser --version
          else
            echo "❌ No suitable browser found for PDF generation"
          fi
        fi
      
    - name: Run security scan with SSE
      id: scan
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        chmod +x ./entrypoint.sh
        ./entrypoint.sh
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        REPORT_FORMAT: ${{ inputs.report_format }}
        TIMEOUT_SECONDS: ${{ inputs.timeout_seconds }}
        EXCLUDE_FILES: ${{ inputs.exclude_files }}
        BLOCKING: ${{ inputs.blocking }}
        BLOCK_PERCENTAGE: ${{ inputs.block_percentage }}
      
